# Generated by Django 4.2.5 on 2023-10-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_grup_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Categories',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
