# Generated by Django 4.2.5 on 2023-10-01 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_group_categories_delete_hashtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('categorie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='blog.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subcategorie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='blog.subcategories')),
            ],
        ),
    ]
