# Generated by Django 4.2.5 on 2023-10-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_subcategories_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posts',
        ),
    ]
