# Generated by Django 4.2.5 on 2023-10-01 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_post_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='subcategorie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorie', to='blog.subcategories'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='categorie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='blog.categories'),
        ),
    ]
