# Generated by Django 4.2.5 on 2023-10-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_posts_subcategorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='subcategorie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.subcategories'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='categorie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorie', to='blog.categories'),
        ),
    ]
