# Generated by Django 4.2.5 on 2023-10-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_categories_fecha_creacion_posts_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archivo',
            new_name='Archivos',
        ),
        migrations.RenameModel(
            old_name='Codigo',
            new_name='Codigos',
        ),
        migrations.RenameModel(
            old_name='Imagen',
            new_name='Imagens',
        ),
        migrations.RenameModel(
            old_name='Texto',
            new_name='Textos',
        ),
        migrations.RenameModel(
            old_name='Titulo',
            new_name='Titulos',
        ),
    ]
