# Generated by Django 4.2.5 on 2023-10-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_archivo_archivos_rename_codigo_codigos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagens',
            new_name='Imagenes',
        ),
    ]
