# Generated by Django 4.2.5 on 2023-10-02 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_imagens_imagenes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='subcategorie',
            new_name='subcategory',
        ),
        migrations.AlterField(
            model_name='archivos',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='blog.posts'),
        ),
        migrations.AlterField(
            model_name='codigos',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to='blog.posts'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='blog.posts'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='categorie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='blog.categories'),
        ),
        migrations.AlterField(
            model_name='textos',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textos', to='blog.posts'),
        ),
        migrations.AlterField(
            model_name='titulos',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='blog.posts'),
        ),
    ]
