# Generated by Django 4.2.5 on 2023-10-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_subcategorie_posts_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategories',
            old_name='categorie',
            new_name='category',
        ),
    ]
