# Generated by Django 4.2.5 on 2023-10-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_categorie_subcategories_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='codigos',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='archivo',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='textos',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='titulos',
            name='contenido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
