# Generated by Django 4.2.5 on 2023-10-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_archivos_archivo_alter_archivos_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigos',
            name='lenguaje',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
